name: upload HTML documentation, PyPI distribution
on: 
  workflow_call:
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      OS: linux
      PYTHON: '3.8'
    steps:
    - name: set package metadata
      run: |
        echo "VERSION=$(echo "${{ github.ref }}" | cut -d/ -f3)" >> $GITHUB_ENV
        echo "PACKAGE=$(echo "${{ github.repository }}" | cut -d/ -f2)" >> $GITHUB_ENV 
    - name: checkout the repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ env.VERSION }}
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: build a sdist
      run: |
        echo ${{ env.VERSION }} > VERSION
        make package
        make test
    - name: build HTML documentation 
      run: |
        make docs
    - name : generate changelog
      run: |
        for pr in $(gh pr list -s merged | grep -i releas | cut -f 1 ); do gh pr view $pr --json title,body,mergedAt --template '{{printf "\n"}}## {{.title}} ({{timefmt "2006-01-02" .mergedAt}}){{printf "\n"}}{{.body}}{{printf "\n"}}'; done > CHANGELOG.md
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: configure clamsbot git user
      run: |
        git config --local user.email "admin@clams.ai"
        git config --local user.name "clams-bot"
    - name: commit the built documentation 
      run: |
        git add docs documentation CHANGELOG.md
        git add -u docs
        git commit -m 'adding HTML documentation for publication'
    - name: push the documentation commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_CLAMSBOT_TOKEN }}
        branch: main
    - name: upload to the official pypi
      run: |
        twine upload -u __token__ -p ${{ secrets.PYPITOKEN }} dist/${{ env.PACKAGE }}-${{ env.VERSION }}.tar.gz 
